### ISSUE TITLE
Query inner/complex object

### ISSUE THREAD

**Issue by developer82** [dan-eyles/sculejs#53]
I have a document that I have saved:
{
   prop1: 'value',
   prop2: 'value',
   complexProp: {
      myVal: 1
   }
}

now I would like all documents where myVal is the same as the value I have in a variable.
I try to do:
var val = 1;
collection.find({ 'complexProp.myVal': val }, { }, function(documents) {
    // come code
});

But I get the error:
null is not an object (evaluating 'o[p.pop()]')

Funny thing is that it used to work - but something had changed and I don't know what...
How can I query an object in such way?

**Comment by dan-eyles** [comment]
Heya, which platform are you experiencing this issue on? I wrote a test case using the code you've provided and it works as expected under node (v0.11.16 and v0.10.36).
